// pays-frontaliers-fr.js
// Pays du monde et frontières terrestres (noms en français)

const paysFrontaliers = {

  "Afghanistan": ["Chine", "Iran", "Pakistan", "Tadjikistan", "Turkménistan", "Ouzbékistan"],
  "Albanie": ["Grèce", "Kosovo", "Macédoine du Nord", "Monténégro"],
  "Algérie": ["Libye", "Mali", "Mauritanie", "Maroc", "Niger", "Tunisie"],
  "Allemagne": ["Autriche", "Belgique", "Danemark", "France", "Luxembourg", "Pays-Bas", "Pologne", "République tchèque", "Suisse"],
  "Andorre": ["France", "Espagne"],
  "Angleterre": ["Écosse", "Pays de Galles"],
  "Angola": ["Botswana", "République démocratique du Congo", "Namibie", "Zambie"],
  "Arabie saoudite": ["Émirats arabes unis", "Irak", "Jordanie", "Koweït", "Oman", "Qatar", "Yémen"],
  "Argentine": ["Bolivie", "Brésil", "Chili", "Paraguay", "Uruguay"],
  "Arménie": ["Azerbaïdjan", "Géorgie", "Iran", "Turquie"],
  "Autriche": ["Allemagne", "Hongrie", "Italie", "Liechtenstein", "République tchèque", "Slovaquie", "Slovénie", "Suisse"],
  "Azerbaïdjan": ["Arménie", "Géorgie", "Iran", "Russie", "Turquie"],

  "Bahreïn": [],
  "Bangladesh": ["Birmanie", "Inde"],
  "Belgique": ["Allemagne", "France", "Luxembourg", "Pays-Bas"],
  "Belize": ["Guatemala", "Mexique"],
  "Bénin": ["Burkina Faso", "Niger", "Nigeria", "Togo"],
  "Bhoutan": ["Chine", "Inde"],
  "Bolivie": ["Argentine", "Brésil", "Chili", "Paraguay", "Pérou"],
  "Bosnie-Herzégovine": ["Croatie", "Monténégro", "Serbie"],
  "Botswana": ["Afrique du Sud", "Namibie", "Zambie", "Zimbabwe"],
  "Brésil": ["Argentine", "Bolivie", "Colombie", "Guyana", "Paraguay", "Pérou", "Suriname", "Uruguay", "Venezuela", "France (Guyane)"],
  "Bulgarie": ["Grèce", "Macédoine du Nord", "Roumanie", "Serbie", "Turquie"],
  "Burkina Faso": ["Bénin", "Côte d’Ivoire", "Ghana", "Mali", "Niger", "Togo"],
  "Burundi": ["Rwanda", "Tanzanie", "République démocratique du Congo"],

  "Cambodge": ["Laos", "Thaïlande", "Viêt Nam"],
  "Cameroun": ["Centrafrique", "Congo", "Gabon", "Guinée équatoriale", "Nigéria", "Tchad"],
  "Canada": ["États-Unis"],
  "Centrafrique": ["Cameroun", "Congo", "République démocratique du Congo", "Soudan", "Soudan du Sud", "Tchad"],
  "Chili": ["Argentine", "Bolivie", "Pérou"],
  "Chine": ["Afghanistan", "Bhoutan", "Corée du Nord", "Inde", "Kazakhstan", "Kirghizistan", "Laos", "Mongolie", "Myanmar", "Népal", "Pakistan", "Russie", "Tadjikistan", "Viêt Nam"],
  "Chypre": [],
  "Colombie": ["Brésil", "Équateur", "Panama", "Pérou", "Venezuela"],
  "Corée du Nord": ["Chine", "Corée du Sud", "Russie"],
  "Corée du Sud": ["Corée du Nord"],
  "Costa Rica": ["Nicaragua", "Panama"],
  "Côte d’Ivoire": ["Burkina Faso", "Ghana", "Guinée", "Libéria", "Mali"],
  "Croatie": ["Bosnie-Herzégovine", "Hongrie", "Monténégro", "Serbie", "Slovénie"],
  "Cuba": [],

  "Danemark": ["Allemagne"],
  "Djibouti": ["Érythrée", "Éthiopie", "Somalie"],
  "Dominique": [],
  "Écosse": ["Angleterre"],
  "Égypte": ["Israël", "Libye", "Soudan"],
  "Émirats arabes unis": ["Arabie saoudite", "Oman"],
  "Équateur": ["Colombie", "Pérou"],
  "Érythrée": ["Djibouti", "Éthiopie", "Soudan"],
  "Espagne": ["Andorre", "France", "Gibraltar", "Portugal", "Maroc"],
  "Estonie": ["Lettonie", "Russie"],
  "Eswatini": ["Afrique du Sud", "Mozambique"],
  "États-Unis": ["Canada", "Mexique"],
  "Éthiopie": ["Djibouti", "Érythrée", "Kenya", "Somalie", "Soudan", "Soudan du Sud"],

  "Finlande": ["Norvège", "Russie", "Suède"],
  "France": ["Allemagne", "Andorre", "Belgique", "Espagne", "Italie", "Luxembourg", "Monaco", "Suisse", "Brésil", "Suriname"],
  "Gabon": ["Cameroun", "Congo", "Guinée équatoriale"],
  "Gambie": ["Sénégal"],
  "Géorgie": ["Arménie", "Azerbaïdjan", "Russie", "Turquie"],
  "Ghana": ["Burkina Faso", "Côte d’Ivoire", "Togo"],
  "Grèce": ["Albanie", "Bulgarie", "Macédoine du Nord", "Turquie"],
  "Guatemala": ["Belize", "Honduras", "Mexique", "Salvador"],
  "Guinée": ["Côte d’Ivoire", "Guinée-Bissau", "Libéria", "Mali", "Sénégal", "Sierra Leone"],
  "Guyana": ["Brésil", "Suriname", "Venezuela"],

  "Haïti": ["République dominicaine"],
  "Honduras": ["Guatemala", "Nicaragua", "Salvador"],
  "Hongrie": ["Autriche", "Croatie", "Roumanie", "Serbie", "Slovaquie", "Slovénie", "Ukraine"],

  "Inde": ["Bangladesh", "Bhoutan", "Birmanie", "Chine", "Népal", "Pakistan"],
  "Indonésie": ["Malaisie", "Papouasie-Nouvelle-Guinée", "Timor oriental"],
  "Iran": ["Afghanistan", "Arménie", "Azerbaïdjan", "Irak", "Pakistan", "Turkménistan", "Turquie"],
  "Irak": ["Arabie saoudite", "Iran", "Jordanie", "Koweït", "Syrie", "Turquie"],
  "Irlande": [],
  "Islande": [],
  "Israël": ["Égypte", "Jordanie", "Liban", "Syrie"],
  "Italie": ["Autriche", "France", "Saint-Marin", "Slovénie", "Suisse", "Vatican"],

  "Japon": [],
  "Jordanie": ["Arabie saoudite", "Irak", "Israël", "Syrie"],

  "Kazakhstan": ["Chine", "Kirghizistan", "Ouzbékistan", "Russie", "Turkménistan"],
  "Kenya": ["Éthiopie", "Ouganda", "Soudan du Sud", "Somalie", "Tanzanie"],
  "Kosovo": ["Albanie", "Macédoine du Nord", "Monténégro", "Serbie"],
  "Koweït": ["Arabie saoudite", "Irak"],

  "Laos": ["Birmanie", "Cambodge", "Chine", "Thaïlande", "Viêt Nam"],
  "Lettonie": ["Biélorussie", "Estonie", "Lituanie", "Russie"],
  "Liban": ["Israël", "Syrie"],
  "Libéria": ["Côte d’Ivoire", "Guinée", "Sierra Leone"],
  "Libye": ["Algérie", "Égypte", "Niger", "Soudan", "Tchad", "Tunisie"],
  "Liechtenstein": ["Autriche", "Suisse"],
  "Lituanie": ["Biélorussie", "Lettonie", "Pologne", "Russie"],
  "Luxembourg": ["Allemagne", "Belgique", "France"],

  "Macédoine du Nord": ["Albanie", "Bulgarie", "Grèce", "Kosovo", "Serbie"],
  "Madagascar": [],
  "Malaisie": ["Brunei", "Indonésie", "Thaïlande"],
  "Malawi": ["Mozambique", "Tanzanie", "Zambie"],
  "Mali": ["Algérie", "Burkina Faso", "Guinée", "Mauritanie", "Niger", "Sénégal"],
  "Maroc": ["Algérie", "Espagne", "Mauritanie"],
  "Mexique": ["Belize", "Guatemala", "États-Unis"],
  "Moldavie": ["Roumanie", "Ukraine"],
  "Mongolie": ["Chine", "Russie"],
  "Monténégro": ["Albanie", "Bosnie-Herzégovine", "Croatie", "Kosovo", "Serbie"],
  "Mozambique": ["Afrique du Sud", "Eswatini", "Malawi", "Tanzanie", "Zambie", "Zimbabwe"],
  "Myanmar": ["Bangladesh", "Chine", "Inde", "Laos", "Thaïlande"],

  "Namibie": ["Afrique du Sud", "Angola", "Botswana", "Zambie"],
  "Népal": ["Chine", "Inde"],
  "Nicaragua": ["Costa Rica", "Honduras"],
  "Niger": ["Algérie", "Bénin", "Burkina Faso", "Libye", "Mali", "Nigeria", "Tchad"],
  "Nigeria": ["Bénin", "Cameroun", "Niger", "Tchad"],
  "Norvège": ["Finlande", "Russie", "Suède"],

  "Ouganda": ["Kenya", "Rwanda", "Soudan du Sud", "Tanzanie", "République démocratique du Congo"],
  "Ouzbékistan": ["Afghanistan", "Kazakhstan", "Kirghizistan", "Tadjikistan", "Turkménistan"],

  "Pakistan": ["Afghanistan", "Chine", "Inde", "Iran"],
  "Panama": ["Colombie", "Costa Rica"],
  "Paraguay": ["Argentine", "Bolivie", "Brésil"],
  "Pays de Galles": ["Angleterre"],
  "Pays-Bas": ["Allemagne", "Belgique"],
  "Pérou": ["Bolivie", "Brésil", "Chili", "Colombie", "Équateur"],
  "Pologne": ["Allemagne", "Biélorussie", "Lituanie", "République tchèque", "Russie", "Slovaquie", "Ukraine"],
  "Portugal": ["Espagne"],

  "Qatar": ["Arabie saoudite"],

  "Roumanie": ["Bulgarie", "Hongrie", "Moldavie", "Serbie", "Ukraine"],
  "Russie": ["Azerbaïdjan", "Biélorussie", "Chine", "Corée du Nord", "Estonie", "Finlande", "Géorgie", "Kazakhstan", "Lettonie", "Lituanie", "Mongolie", "Norvège", "Pologne", "Ukraine"],
  "Rwanda": ["Burundi", "Ouganda", "République démocratique du Congo", "Tanzanie"],

  "Saint-Marin": ["Italie"],
  "Salvador": ["Guatemala", "Honduras"],
  "Sénégal": ["Gambie", "Guinée", "Guinée-Bissau", "Mali", "Mauritanie"],
  "Serbie": ["Bosnie-Herzégovine", "Bulgarie", "Croatie", "Hongrie", "Kosovo", "Macédoine du Nord", "Monténégro", "Roumanie"],
  "Slovaquie": ["Autriche", "Hongrie", "Pologne", "République tchèque", "Ukraine"],
  "Slovénie": ["Autriche", "Croatie", "Hongrie", "Italie"],
  "Somalie": ["Djibouti", "Éthiopie", "Kenya"],
  "Soudan": ["Centrafrique", "Égypte", "Érythrée", "Éthiopie", "Libye", "Soudan du Sud", "Tchad"],
  "Soudan du Sud": ["Centrafrique", "Éthiopie", "Kenya", "Ouganda", "République démocratique du Congo", "Soudan"],
  "Suède": ["Finlande", "Norvège"],
  "Suisse": ["Allemagne", "Autriche", "France", "Italie", "Liechtenstein"],
  "Syrie": ["Irak", "Israël", "Jordanie", "Liban", "Turquie"],

  "Tadjikistan": ["Afghanistan", "Chine", "Kirghizistan", "Ouzbékistan"],
  "Tanzanie": ["Burundi", "Kenya", "Malawi", "Mozambique", "Ouganda", "Rwanda", "Zambie"],
  "Tchad": ["Cameroun", "Centrafrique", "Libye", "Niger", "Nigeria", "Soudan"],
  "Thaïlande": ["Birmanie", "Cambodge", "Laos", "Malaisie"],
  "Timor oriental": ["Indonésie"],
  "Togo": ["Bénin", "Burkina Faso", "Ghana"],
  "Tunisie": ["Algérie", "Libye"],
  "Turkménistan": ["Afghanistan", "Iran", "Kazakhstan", "Ouzbékistan"],
  "Turquie": ["Arménie", "Azerbaïdjan", "Bulgarie", "Géorgie", "Grèce", "Iran", "Irak", "Syrie"],

  "Ukraine": ["Biélorussie", "Hongrie", "Moldavie", "Pologne", "Roumanie", "Russie", "Slovaquie"],
  "Uruguay": ["Argentine", "Brésil"],

  "Vatican": ["Italie"],
  "Venezuela": ["Brésil", "Colombie", "Guyana"],
  "Viêt Nam": ["Cambodge", "Chine", "Laos"],

  "Yémen": ["Arabie saoudite", "Oman"],
  "Zambie": ["Angola", "Botswana", "Malawi", "Mozambique", "Namibie", "République démocratique du Congo", "Tanzanie", "Zimbabwe"],
  "Zimbabwe": ["Afrique du Sud", "Botswana", "Mozambique", "Zambie"]

};

export default paysFrontaliers;
